name: Funkin' Rewritten

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  first:
    name: 3DS
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitarm
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make ctr
        
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
      
      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo 3DS-${{ steps.commit.outputs.short }}
          path: |
            platform/3ds/*.elf
            platform/3ds/*.3dsx

  second:
    name: Switch
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkita64
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make hac
      
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
        
      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo Switch-${{ steps.commit.outputs.short }}
          path: |
            platform/switch/*.elf
            platform/switch/*.nro
